### ISSUE TITLE
Contact Link 

### ISSUE THREAD

**Issue by Elizabeth1998** [hacksu/2018-Hacksu-ui-main#1]
The Contact Link in Section 1 of the website is not available. Where the link needs to be send to also needs to be determined. Should it go to the bottom of the page where the contact section is located or should it send the users to another application?

**Comment by bhollan5** [comment]
It could be a "mailto" link, like this, as another option:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto

Imo i'd go with a separate route, probably, similar to what we currently have:
http://hacksu.cs.kent.edu/contact
but idk

**Comment by Elizabeth1998** [comment]
The separate route that we currently have is a great idea! We can resign the contact page
