### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by Elizabeth1998** [hacksu/2018-Hacksu-ui-main#5]
The social media icons located near the GitHub icon at the bottom of the page are there; however, they are not visible. Twitter, Facebook, and Instagram cannot be seen, and they need to be. This issue involves making those account icons visible.

**Comment by dkelsey3** [comment]
Hey guys!

Not sure what is wrong. Alex, Brad and I took a look but the pictures aren't showing up (changing colors didn't show that there were actual logos). Is there something wrong with the logo and it is nonexistant?
